[akash-provider] do not issue TX when not needed
Changes:

- bump akash-provider chart to 0.153.0
- install bc
- check Akash RPC node is not 30 seconds behind/ahead before continuing
- do not append provider.yaml but rather create it from scratch
- figure the provider address in case the user passes `--from=<key_name>` instead of `--from=<akash1...>` address
- check provider existence on the blockchain before attempting to create
  a new one (`akash tx provider create provider.yaml ...`)
- check whether provider settings (host uri, attributes, ...) have changed
  before broadcasting the new ones on the blockchain (`akash tx provider
update provider.yaml ...`)
- before generating and broadcasting the new provider certificate
  - check the last provider certificate found on the blockchain is valid
  - check whether the last provider certificate serial number found on the blockchain
  matches the local one

Issues addressed:

- fixes #35
- fixes #9

diff --git a/charts/akash-provider/templates/configmap-boot.yaml b/charts/akash-provider/templates/configmap-boot.yaml
--- a/charts/akash-provider/templates/configmap-boot.yaml
+++ b/charts/akash-provider/templates/configmap-boot.yaml
@@ -17,18 +17,35 @@ data:
     ##
     # Check the Akash Node is working
     ##
-    apt update && apt -yqq install curl jq netcat
+    apt update && apt -yqq install curl jq bc netcat
     solo_ip=$(echo $AKASH_NODE | cut -d":" -f2 | cut -d "/" -f3) ; port=$(echo $AKASH_NODE | cut -d":" -f3-)
     if [[ $AKASH_NODE != "http://akash-node-1:26657" ]]; then
       nc -z -v -w5 $solo_ip $port
     fi
     until [[ $(curl -s $AKASH_NODE/status | jq -r .result.sync_info.catching_up) == "false" ]]; do sleep 15; echo "Akash node not ready. Retrying";  done
-    
+
+    # Check Akash RPC node isn't running behind too much and abort if it does.
+    DATE_AKASH=$(akash status | jq -r '.SyncInfo.latest_block_time')
+    TS_AKASH=$(date +%s --date "$DATE_AKASH")
+    TS=$(date +%s)
+    DIFF=$(echo "$TS - $TS_AKASH" | bc)
+    if [[ "$DIFF" -gt 30 ]]; then
+      echo "Akash RPC $AKASH_NODE is running $DIFF seconds behind."
+      echo "ACTION: Make sure your system time in synchronized and/or check your Akash RPC node."
+      exit 1
+    elif [[ "$DIFF" -lt -30 ]]; then
+      echo "Akash RPC $AKASH_NODE is running $DIFF seconds ahead."
+      echo "ACTION: Make sure your system time in synchronized and/or check your Akash RPC node."
+      exit 1
+    else
+      echo "Last block Akash RPC $AKASH_NODE seen was $DIFF seconds ago => OK"
+    fi
+
     ##
     # Create Provider
     ##
 
-    cat <<EOT >> provider.yaml
+    cat <<EOT > provider.yaml
     host: https://provider.{{ .Values.domain }}:8443
     attributes:
     {{- range $key, $val := .Values.attributes }}
@@ -37,7 +54,20 @@ data:
     {{- end }}
     EOT
 
-    /bin/akash tx provider create provider.yaml >deploy.log 2>&1 ; DEPLOY=$(cat deploy.log)
+    # Figure the provider address in case the user passes `--from=<key_name>` instead of `--from=<akash1...>` address.
+    PROVIDER_ADDRESS="$(/bin/akash keys show $AKASH_FROM -a)"
+    if [[ -z "$PROVIDER_ADDRESS" ]]; then
+      echo "PROVIDER_ADDRESS variable is empty. Something went wrong"
+      exit 1
+    fi
+
+    /bin/akash query provider get $PROVIDER_ADDRESS -o json
+    if [[ $? -ne 0 ]]; then
+      echo "Could not find provider: $PROVIDER_ADDRES on the blockchain when querying Akash RPC node: $AKASH_NODE"
+      echo "Attempting to create a new provider ..."
+      /bin/akash tx provider create provider.yaml >deploy.log 2>&1
+      DEPLOY=$(cat deploy.log)
+    fi
 
     if [[ $DEPLOY == *"incorrect account sequence"* ]]; then
       echo "Provider has issue talking to the node, check NODE is synced."
@@ -51,30 +81,64 @@ data:
       exit 1
     fi
 
-    /bin/akash tx provider update provider.yaml >deploy.log 2>&1 ; DEPLOY=$(cat deploy.log)
+    PROVIDER_IN_CHAIN="$(akash query provider get $PROVIDER_ADDRESS -o json | jq | sha1sum | awk '{print $1}')"
+    PROVIDER_LOCAL_FILE="$(/bin/akash tx provider update provider.yaml --offline --generate-only --from $PROVIDER_ADDRESS | jq -r '.body.messages[]' | jq -r 'del(."@type")' | sha1sum | awk '{print $1}')"
+    if [[ "$PROVIDER_IN_CHAIN" != "$PROVIDER_LOCAL_FILE" ]]; then
+      echo "Updating provider in the blockchain ..."
+      /bin/akash tx provider update provider.yaml >deploy.log 2>&1
+      DEPLOY=$(cat deploy.log)
 
-    if [[ $DEPLOY == *"insufficient fees"* ]]; then
-      echo "Insufficient fees!  Change the fee settings."
-      exit 1
+      if [[ $DEPLOY == *"insufficient fees"* ]]; then
+        echo "Insufficient fees!  Change the fee settings."
+        exit 1
+      fi
+
+      if [[ $DEPLOY == *"out of gas in location"* ]]; then
+        echo "Out of gas!  Change gas/fee settings."
+        exit 1
+      fi
+
+      if [[ $DEPLOY == *"incorrect account sequence"* ]]; then
+        echo "Provider has issue talking to the node, check NODE is synced."
+        exit 1
+      fi
+
+      if [[ $DEPLOY == *"Error"* ]]; then
+        echo "Error creating provider : $DEPLOY"
+        exit 1
+      fi
     fi
 
-    if [[ $DEPLOY == *"out of gas in location"* ]]; then
-      echo "Out of gas!  Change gas/fee settings."
-      exit 1
+    GEN_NEW_CERT=1 # 0 = yes; otherwise do not (re-)generate new provider certificate
+    LAST_CERT_STATUS="$(akash query cert list --owner $PROVIDER_ADDRESS --state valid -o json | jq -r '.certificates[-1].certificate.state')"
+    # Check whether the last broadcasted certificate is valid
+    if [[ "valid" != "$LAST_CERT_STATUS" ]]; then
+      echo "No valid certificate found for provider: $PROVIDER_ADDRESS"
+      GEN_NEW_CERT=0
     fi
 
-    if [[ $DEPLOY == *"incorrect account sequence"* ]]; then
-      echo "Provider has issue talking to the node, check NODE is synced."
-      exit 1
+    # Check whether the local certificate matches the one on the blockchain
+    LOCAL_CERT_SN="$(cat ${AKASH_HOME}/${PROVIDER_ADDRESS}.pem | openssl x509 -serial -noout)"
+    REMOTE_CERT_SN="$(akash query cert list --owner $PROVIDER_ADDRESS --state valid | jq -r '.certificates[-1].certificate.cert' | openssl base64 -A -d | openssl x509 -serial -noout)"
+    if [[ -z "$LOCAL_CERT_SN" ]]; then
+      echo "LOCAL_CERT_SN variable is empty. Most likely ${AKASH_HOME}/${PROVIDER_ADDRESS}.pem is missing"
+      GEN_NEW_CERT=0
     fi
 
-    if [[ $DEPLOY == *"Error"* ]]; then
-      echo "Error creating provider : $DEPLOY"
-      exit 1
+    if [[ -z "$REMOTE_CERT_SN" ]]; then
+      echo "REMOTE_CERT_SN variable is empty. Most likely the cert hasn't been broadcasted to the blockchain yet."
+      GEN_NEW_CERT=0
+    elif [[ "$LOCAL_CERT_SN" != "$REMOTE_CERT_SN" ]]; then
+      echo "Local certificate SN does not match the one on the blockchain"
+      GEN_NEW_CERT=0
     fi
 
-    /bin/akash tx cert generate server provider.{{ .Values.domain }}
-    /bin/akash tx cert publish server
+    if [[ $GEN_NEW_CERT ]]; then
+      echo "Generating new provider certificate"
+      /bin/akash tx cert generate server provider.{{ .Values.domain }}
+      echo "Publishing new provider certificate"
+      /bin/akash tx cert publish server
+    fi
 
     ##
     # Run daemon
