akash-provider: fixes for Akash 0.15.0-rc15 to work (#26)
* akash-provider: do not fail faster than we can analyze the log

without that fix akash v0.15.0-rc15 just silently quits here:

```
...
+ /bin/akash tx provider create provider.yaml
```

* akash-provider: fix the error check logic

"akash tx provider create" should not exit when the provider already
exists, e.g.:

```
Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: id: akash1tzjgwel88adq836r2a0sw6mxl75xmr666pe375: invalid provider: already exists: invalid request
```

diff --git a/charts/akash-provider/templates/configmap-boot.yaml b/charts/akash-provider/templates/configmap-boot.yaml
--- a/charts/akash-provider/templates/configmap-boot.yaml
+++ b/charts/akash-provider/templates/configmap-boot.yaml
@@ -7,7 +7,7 @@ data:
   run.sh: |
     #!/bin/bash
 
-    set -ex
+    set -x
 
     ##
     # Import key
@@ -44,13 +44,11 @@ data:
       exit 1
     fi
 
-    if [[ $DEPLOY == *"Error"* ]]; then
-      echo "Error creating provider : $DEPLOY"
-      exit 1
-    fi
-
     if [[ $DEPLOY == *"already exists"* ]]; then
       echo "Provider already exists, continue..."
+    elif [[ $DEPLOY == *"Error"* ]]; then
+      echo "Error creating provider : $DEPLOY"
+      exit 1
     fi
 
     /bin/akash tx provider update provider.yaml >deploy.log 2>&1 ; DEPLOY=$(cat deploy.log)
